export const actionsEnums = {
  // Members
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
  // User
  INDIVIDUAL_USER_REQUEST: 'INDIVIDUAL_USER_REQUEST',
  // Interactions
  UPDATE_ORG_NAME_INPUT: 'UPDATE_ORG_NAME_INPUT',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_MEMBERS_PER_PAGE: 'CHANGE_MEMBERS_PER_PAGE',
};
